"""
==============================================================
OptionForge
research/trade.py
--------------------------------------------------------------
Immutable Research Trade Model
==============================================================
"""

from dataclasses import dataclass
from datetime import date
from uuid import UUID

from optionforge.research.signal import Signal


@dataclass(frozen=True, slots=True)
class Trade:
    """
    Immutable research trade.

    Represents one completed historical trade generated by a
    research strategy.
    """

    trade_id: UUID

    strategy_id: str
    strategy_version: str

    symbol: str

    signal: Signal

    signal_date: date
    entry_date: date
    exit_date: date

    entry_price: float
    exit_price: float

    return_pct: float

    holding_days: int