"""
============================================================
OptionForge
Order
============================================================

Author      : OptionForge
Module      : order.py

Purpose
-------
Immutable institutional order.

Represents a single executable order generated by
the Execution Engine.

============================================================
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any, Mapping

from optionforge.execution.order_side import OrderSide
from optionforge.execution.order_status import OrderStatus
from optionforge.execution.order_type import OrderType


@dataclass(
    frozen=True,
    slots=True,
)
class Order:
    """
    Immutable institutional order.
    """

    # -----------------------------------------------------
    # Identity
    # -----------------------------------------------------

    symbol: str

    side: OrderSide

    order_type: OrderType

    status: OrderStatus

    # -----------------------------------------------------
    # Quantity
    # -----------------------------------------------------

    quantity: int

    # -----------------------------------------------------
    # Pricing
    # -----------------------------------------------------

    price: float

    # -----------------------------------------------------
    # Metadata
    # -----------------------------------------------------

    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC),
        compare=False,
    )

    metadata: Mapping[str, Any] = field(
        default_factory=dict,
        compare=False,
    )

    # -----------------------------------------------------
    # Validation
    # -----------------------------------------------------

    def __post_init__(self) -> None:

        if not self.symbol.strip():

            raise ValueError("symbol cannot be empty.")

        if self.quantity <= 0:

            raise ValueError("quantity must be positive.")

        if self.price < 0:

            raise ValueError("price cannot be negative.")

    # -----------------------------------------------------
    # Convenience
    # -----------------------------------------------------

    @property
    def is_buy(self) -> bool:

        return self.side.is_buy

    @property
    def is_sell(self) -> bool:

        return self.side.is_sell

    @property
    def is_market(self) -> bool:

        return self.order_type.is_market

    @property
    def is_limit(self) -> bool:

        return self.order_type.is_limit

    @property
    def is_open(self) -> bool:

        return self.status.is_open

    @property
    def is_closed(self) -> bool:

        return self.status.is_closed

    @property
    def notional_value(self) -> float:
        """
        Order value.
        """

        return self.quantity * self.price

    # -----------------------------------------------------
    # Serialization
    # -----------------------------------------------------

    def to_dict(
        self,
    ) -> dict[str, Any]:

        return {
            "symbol": self.symbol,
            "side": self.side.name,
            "order_type": self.order_type.name,
            "status": self.status.name,
            "quantity": self.quantity,
            "price": self.price,
            "notional_value": self.notional_value,
            "created_at": self.created_at.isoformat(),
            "metadata": dict(self.metadata),
        }

    # -----------------------------------------------------
    # Representation
    # -----------------------------------------------------

    def __str__(
        self,
    ) -> str:

        return f"Order(" f"{self.side.name} " f"{self.quantity} " f"{self.symbol})"

    def __repr__(
        self,
    ) -> str:

        return (
            f"Order("
            f"symbol={self.symbol!r}, "
            f"side={self.side.name}, "
            f"type={self.order_type.name}, "
            f"status={self.status.name})"
        )
