"""
============================================================
OptionForge
Knowledge Type
============================================================

Author      : OptionForge
Module      : knowledge_type.py

Purpose
-------
Defines the high-level categories of institutional
market knowledge.

KnowledgeType classifies conclusions generated by the
Knowledge Framework.

These are NOT analytics or indicators.

They represent market understanding.

Examples
--------
VOLATILITY
DEALER
TREND
LIQUIDITY
FLOW
MARKET_STRUCTURE
RISK
REGIME
============================================================
"""

from __future__ import annotations

from enum import Enum, auto


class KnowledgeType(Enum):
    """
    High-level institutional knowledge categories.
    """

    # =====================================================
    # Market Structure
    # =====================================================

    MARKET_STRUCTURE = auto()

    # =====================================================
    # Dealer Positioning
    # =====================================================

    DEALER = auto()

    # =====================================================
    # Volatility
    # =====================================================

    VOLATILITY = auto()

    # =====================================================
    # Trend
    # =====================================================

    TREND = auto()

    # =====================================================
    # Liquidity
    # =====================================================

    LIQUIDITY = auto()

    # =====================================================
    # Order Flow
    # =====================================================

    FLOW = auto()

    # =====================================================
    # Risk
    # =====================================================

    RISK = auto()

    # =====================================================
    # Market Regime
    # =====================================================

    REGIME = auto()
