"""
============================================================
OptionForge
Evidence Registry
============================================================

Author      : OptionForge
Module      : evidence_registry.py
Purpose     : Immutable registry of institutional evidence.

The EvidenceRegistry stores every piece of Evidence
generated by the EvidenceEngine.

============================================================
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator

from optionforge.evidence.evidence import Evidence
from optionforge.evidence.evidence_type import EvidenceType


class EvidenceRegistry:
    """
    Immutable registry of institutional evidence.
    """

    def __init__(self) -> None:

        self._evidence: dict[str, Evidence] = {}

    # -----------------------------------------------------
    # Registration
    # -----------------------------------------------------

    def add(
        self,
        evidence: Evidence,
    ) -> None:
        """
        Add evidence to registry.

        Raises
        ------
        ValueError
            If duplicate evidence id exists.
        """

        if evidence.id in self._evidence:

            raise ValueError(f"Duplicate Evidence id: {evidence.id}")

        self._evidence[evidence.id] = evidence

    # -----------------------------------------------------
    # Lookup
    # -----------------------------------------------------

    def get(
        self,
        evidence_id: str,
    ) -> Evidence:
        """
        Return evidence by id.
        """

        return self._evidence[evidence_id]

    def contains(
        self,
        evidence_id: str,
    ) -> bool:

        return evidence_id in self._evidence

    # -----------------------------------------------------
    # Filtering
    # -----------------------------------------------------

    def by_type(
        self,
        evidence_type: EvidenceType,
    ) -> tuple[Evidence, ...]:
        """
        Return all evidence of a given type.
        """

        return tuple(
            evidence
            for evidence in self._evidence.values()
            if evidence.type == evidence_type
        )

    # -----------------------------------------------------
    # Statistics
    # -----------------------------------------------------

    @property
    def score(self) -> float:
        """
        Total evidence score.
        """

        return sum(evidence.score for evidence in self._evidence.values())

    @property
    def confidence(self) -> float:
        """
        Average confidence.
        """

        if not self._evidence:

            return 0.0

        return sum(evidence.confidence for evidence in self._evidence.values()) / len(
            self._evidence
        )

    # -----------------------------------------------------
    # Collection API
    # -----------------------------------------------------

    def values(self) -> tuple[Evidence, ...]:

        return tuple(self._evidence.values())

    def items(self):

        return self._evidence.items()

    def __iter__(
        self,
    ) -> Iterator[Evidence]:

        return iter(self._evidence.values())

    def __len__(
        self,
    ) -> int:

        return len(self._evidence)

    def __contains__(
        self,
        evidence_id: str,
    ) -> bool:

        return evidence_id in self._evidence

    # -----------------------------------------------------
    # Serialization
    # -----------------------------------------------------

    def to_dict(self) -> dict[str, dict]:

        return {evidence.id: evidence.to_dict() for evidence in self._evidence.values()}

    # -----------------------------------------------------
    # Representation
    # -----------------------------------------------------

    def __repr__(
        self,
    ) -> str:

        return f"EvidenceRegistry(" f"count={len(self)})"
